spring.application.name=pokedex-api
server.port=420
#spring.datasource.url=jdbc:postgresql://192.168.1.7:5432/main
#spring.datasource.username=admin
#spring.datasource.password=GermanoDSP
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# ===============================
# Configuração do H2 (File-Based)
# ===============================
# Cria uma pasta 'data' na raiz do projeto e salva o arquivo 'pokedex-db' lá
spring.datasource.url=jdbc:h2:file:./builds/pokedex-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# Configuração do JPA / Hibernate
# ===============================
# 'update' cria as tabelas automaticamente se não existirem, e atualiza se você mudar algo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Console do H2 (Interface Web)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CHAVE JWT (ideal é injetar isso pelas variáveis do servido)
# ===============================
api.security.token.secret=${JWT_SECRET:teste-de-token-jwt-1-geeg420}